### ISSUE TITLE
Custom keywords or regular expression for Next Prev Settings

### ISSUE THREAD

**Issue by wsxqaz7878** [roysix/url-incrementer#11]
**Describe the feature request you'd like**
Please describe what the feature request is. The more detailed you can be, the better! Also, is your feature request related to a problem? Ex: I'm always frustrated when [...] or I wish the extension did [...] differently?

There is an addon from Firefox called NextPlease, which support custom keywords or regular expression to define the next or prev, and not only support English keywords.
Would you consider add this feature? Because some sites did not working with current solution.
I just switched from Firefox to Chrome, and found this addon very similar to NextPlease, I would like to see these features on URLI .
BTW, this is the best of same type addon on chrome web store.
 Sorry for my english.

**Screenshots**

If applicable, please add any screenshots that might help explain your feature request better.

![nextplease](https://user-images.githubusercontent.com/85553059/121162408-7c32b880-c880-11eb-86fa-56da90f3e384.png)

**Comment by sixcious** [comment]
Hi wsxqaz7878,

Thanks for opening this issue and for using URLI!

The upcoming Version 6.0 will have support for next/prev keywords, as well as Selector and XPath rules. The [Firefox version of URLI](https://addons.mozilla.org/firefox/addon/url-incrementer/) already supports keywords since it's a beta of 6.0, but the Chrome/Edge versions are a bit behind. My other extension, [Infy Scroll](https://github.com/roysix/infy-scroll), also supports next/prev keywords if you want to check that out in the meantime.

Unfortunately, the regex keywords thing, though, probably won't be implemented, at least not right now. As a rule, I try not to use other people's extensions to avoid copying specific features/ideas from them. (I'll definitely keep it in mind though!)

Thanks again for using URLI!
