### ISSUE TITLE
ER: X button resets more

### ISSUE THREAD

**Issue by CarlFK** [roysix/url-incrementer#14]
the main [ + - x (edit) ] bar, 
The edit button edits the current settings.  (fine, don't change that)
however, I generally need it to parse a new URL and set up new settings,
so it would be handy if after hitting the X the setup UI came up.
I don't see any use in just clearing the settings as nothing 

every time I hit the x, 
I then click off to close the tool bar,
then click the +URL button to open it again to bring up the settings dialog. 

I would like it if the X would clear the current settings and parse the new URL

I can't imagine a case where someone wants the current behavior:  X out the current settings, then Edit /parse the original URL.

So I would like to see: hit the X, bring up the settings dialog using the current URL in the browser.

**Comment by sixcious** [comment]
Hi Carl, thank you for your two great suggestions, and I'm sorry for the super long delay!

I released a new version of URLI last week (Version 6) with the following changes based on your feature request:

- Clear (the X Button) will now set it to the current tab's URL
- I was a little hesitant to make Clear always open the Setup by default because it is also there to do other things like stopping Auto. However, if you go to URLI's Options screen, Right Click anywhere > `Inspect` to open up DevTools, click on the `Console` tab and enter `chrome.storage.local.set({"clearSetup": true});`, it'll open up the Setup automatically after clearing. I can't promise that this setting will be there forever, but I hope this works for the time being.

Thank you again! I hope this helps ❤️
