### ISSUE TITLE
URL Incrementer stopped working for local files?

### ISSUE THREAD

**Issue by alexanderpesch** [roysix/url-incrementer#16]
It looks like it is not working for local files anymore (as of October 17th, 2023):
file:///C:/Users/.../test_01.htm

Firefox 118.0.2 (64-bit)
Chrome 118.0.5993.70 (64-bit)

Can you confirm the issue?

**Comment by sixcious** [comment]
Hi, thanks for opening this issue!

Unfortunately, incrementing local file URLs has never really worked on Firefox due to this issue on Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1266960

For Chromium, you can just follow these steps:
https://github.com/sixcious/url-incrementer/wiki/Local-Files

I hope this helps ❤️

**Comment by alexanderpesch** [comment]
That did the trick for chrome! Thank you so much for this nice little gadget, i use it all the time! 😃
