### ISSUE TITLE
Mouse shortcuts not working in Firefox

### ISSUE THREAD

**Issue by rtripas** [roysix/url-incrementer#18]
### Description

Mouse shortcuts are not working unless I click the url incrementer icon than click accept.  Keyboard shortcuts however work fine.  With version 5 both mouse and keyboard shortcuts used the action settings by default.

### URL

https://slickdeals.net/f/16844270-bank-of-america-customized-cash-rewards-credit-card-spend-1-000-or-more-on-purchases-in-the-first-90-days-of-account-opening-to-earn-a-200-cash-rewards-bonus?page=2

### Version

6

### Browser

Firefox 130

### OS

Windows 11

### Device

PC

**Comment by sixcious** [comment]
Hi rtripas, thank you for opening this issue ❤️ 

Under `OPTIONS > SHORTCUTS`, below the Shortcuts table, do you have the checkbox `Enable Quick Mouse Shortcuts` checked? It is now unchecked by default as a precaution because I didn't want some users firing the mouse shortcuts inadvertently. On the flip side, I was scared some users may miss the checkbox.

Please let me know if this works.

**Comment by rtripas** [comment]
Thanks fixed it, thanks!
