### ISSUE TITLE
No Multi +++ Button in Chrome Extension

### ISSUE THREAD

**Issue by x-vibe** [roysix/url-incrementer#2]
Hi there and thanks for the extension, it looks like it can do exactly what I need it to, download images that change by increments in number of 1..

My URL Structure is as follows:

https://www.site.com/folder123/image123.jpg

I need to increment both the folder and the filename each time, however the extension doesn't do that. I checked your guide:

Multi Incrementing
Multi lets you increment up to 3 parts of the URL individually, simultaneously, or in ranges. You can even increment the same selection in multiple ways (for example, different intervals)! Select the part as normal and optionally adjust the interval or base, then click the Multi +++ button near Selection. Repeat for each additional part, then click Accept. You'll then see a new set of color-coded Increment Decrement buttons allowing you to increment just that one part or simultaneously increment all parts.

...the problem is there is not "MULTI +++" button anywhere to be seen...

![image](https://user-images.githubusercontent.com/19342324/82413982-6260e080-9a87-11ea-9f0b-c209c2d32473.png)

What am I overlooking? Also, it's tough to expect people to know REGEX, maybe a little example would be helpful in the actual extension.

Cheers!

**Comment by sixcious** [comment]
Hi,

Thanks for reporting this. Version 6.0 has the Multi feature, but it hasn't yet been formally released on the Chrome Web Store (Currently 5.8) due to a myriad of "external/administrative" issues (nothing to do with the extension).

The Multi button in 6.0 can be pressed up to three times right; it's right next to the "Selection" label here:

![Capture](https://user-images.githubusercontent.com/1027814/82417615-cc5a9500-9a49-11ea-99b3-fcdaa9563e55.PNG)


For now, the two options I would recommend are to either download the FireFox version (An early 6.0 beta), or, if you know how to, enable Developer Mode in Chrome and download and install the most up to date 6.0 Chrome version here on Github as a "Local Extension." The Chrome version here on GitHub is what I am working on at the moment and has a few more features, but you "should" be able to do what you want with either version.

FireFox 6.0 Beta version
[https://addons.mozilla.org/firefox/addon/url-incrementer/](https://addons.mozilla.org/firefox/addon/url-incrementer/
)

As for the regex, are you talking about the download includes/excludes filters or something else? You don't have to use regex for the filters, you can just enter the text to include/exclude verbatim as is (it's just that the extension will recognize regex if you do use it).

Thanks!

**Comment by colemar** [comment]
There is no src folder in master.
Where can I find Chrome 6.0 Beta version?

**Comment by sixcious** [comment]
Hi @colemar, you're replying to a really old comment from a year ago and things have changed. I replied to you via email. And if anyone else has the same question, please check out #9 for more details on the current status of URLI and Version 6.0. You can try checking out the Firefox version in the mean time until the Chrome version is out if you need the Multi incrementing or some other 6.0 features like Date Time incrementing.

Thanks and sorry for the inconvenience.
