### ISSUE TITLE
program wont load

### ISSUE THREAD

**Issue by steriet1978** [roysix/url-incrementer#23]
### Description

I have been trying for a while to load the extention on bith firefox and chrome but keep getting the same message.  Ive used different computer too to rule things out.  can anyone offer advice

![image](https://github.com/user-attachments/assets/a0d0c230-8d36-4742-8ea3-fcd53294370a)

### URL

all

### Version

newest

### Browser

chrome and fire fox

### OS

11

### Device

PC

**Comment by sixcious** [comment]
Hi steriet1978, thank you for opening this issue ❤️

That definitely doesn't sound right. It looks like it may not have installed correctly for some reason.

Is this happening on every single URL you try clicking the toolbar icon on? Can you confirm that it also happens on the following URL?
https://example.com/?page=1

Also, what happens when you click the Options Button to go to the Options Screen. Are all the settings showing and is the Options Screen functional, allowing you go to different tabs in the Options? Or do the settings look blank/unfilled? Can you show me a screenshot of the Options Screen?

**Comment by sixcious** [comment]
Hi steriet, I'm going to go ahead and close this, but please feel free to reply if you'd like to. Also, I released a new version recently with some improvements/fixes that might help and I completely redid the error handling so it should show a more descriptive error message.

Thank you.
