### ISSUE TITLE
No toolbar icons, no key shortcut info, URLI Firefox

### ISSUE THREAD

**Issue by ublokr** [roysix/url-incrementer#3]
I'm so lost. I add URLI to Firefox 76.0.1 and nothing happens. I see no toolbar icon (nor with the separate + and - addons). Look I'm a new returnee to Firefox (from Pale Moon) so I don't even know where the toolbar is -- top or bottom? Nor how to show/unshow it. Your brief description of URLI mentions no default keyboard shortcuts, perhaps because this is so user-selectable? But at least get me started. How do I increment? Decrement?  Or maybe you haven't updated for the latest Firefox?  Whatever happened to the beautiful "URL Flipper" from years past? You ask dissatisfied users to email you instead of leaving a low Firefox add-on rating, but then nowhere is there your contact information. Is it reasonable to expect users to join GitHub and leave something like this?

**Comment by ublokr** [comment]
How will I know if you reply to this? Will I get an email?

**Comment by roysix** [comment]
Hi @ublokr ,

Let me address your issues one by one. FireFox is also not my main browser, but I'll reply to the browser-specific issues as well. All screenshots below are from FireFox 76.0.1

Re:Toolbar Icon
So, after you install URLI (or any extension), the toolbar icon normally shows up on the toolbar near the **three bar menu icon (Menu)** on the right side of the address bar. It's the URL+ icon underlined in red below.

![1](https://user-images.githubusercontent.com/1027814/83328380-8de68680-a250-11ea-9d3a-7e56447b26a2.PNG)

It is a dark icon, so if your toolbar is a custom dark one, it may not stand out. If you don't have enough room (like having a lot of add-ons installed), it may also not be there. To get it there, Click **Menu > Customize (Paint Brush Icon)** and you'll be taken to this screen where you should see the extension icon and you can drag it onto your toolbar or the overflow menu. Click the **Done** button at the bottom of the screen when finished.

![2](https://user-images.githubusercontent.com/1027814/83328387-9474fe00-a250-11ea-9521-de788db96de5.PNG)

Re: Keyboard / Mouse Shortcuts
The Default is Ctrl+Shift+Up to increment and Ctrl+Shift+Down to decrement. In order to adjust the shortcuts, you need to get into the extension options page. There's two ways.

1. After you get the icon on your toolbar, you can click **URLI Extension Icon > Gear Icon (Options)**
2. Or via the FireFox three bar menu icon, click: **Menu >Add-ons > Extensions > URL Incrementer > Options**

![3](https://user-images.githubusercontent.com/1027814/83329059-2d0d7d00-a255-11ea-83ef-98f055160369.PNG)

From there you can adjust the shortcuts to whatever key and mouse combination you want.

![4](https://user-images.githubusercontent.com/1027814/83329069-33035e00-a255-11ea-8574-780fa3fe8643.PNG)

Sorry you couldn't find my email address and had to resort to GitHub for help. The only reason I didn't put my email on the Help Page is to avoid getting a ton of junk mail from harvesting crawlers who look for it on the web. Per your feedback, I'll put it on the Help page as soon as I am able to (perhaps as an image).

For future reference, my email is listed on the [Add-Ons Page in Firefox](https://addons.mozilla.org/en-US/firefox/addon/url-incrementer/
) under the **More information box** and if you click **Support Email** or on the Extension's own Options page at the bottom. 

Finally, IF this helps, and if that was you who left that 1 star rating an hour ago, I'd appreciate it if you could at least consider adjusting it, considering it took me over an hour to write out this reply with the screenshots (after figuring out how to change my FireFox language back to English). :)

Hope this helps!
Roy

**Comment by sixcious** [comment]
Hi @ublokr ,

I'll try to address your issues one by one. FireFox is also not my main browser, but I'll reply to the browser-specific issues as well. All screenshots below are from FireFox 76.0.1

Re:Toolbar Icon
So, after you install URLI (or any extension), the toolbar icon normally shows up on the toolbar near the **three bar menu icon (Menu)** on the right side of the address bar. It's the URL+ icon underlined in red below.

![1](https://user-images.githubusercontent.com/1027814/83328380-8de68680-a250-11ea-9d3a-7e56447b26a2.PNG)

It is a dark icon, so if your toolbar is a custom dark one, it may not stand out. If you don't have enough room (like having a lot of add-ons installed), it may also not be there. To get it there, Click **Menu > Customize (Paint Brush Icon)** and you'll be taken to this screen where you should see the extension icon and you can drag it onto your toolbar or the overflow menu. Click the **Done** button at the bottom of the screen when finished.

![2](https://user-images.githubusercontent.com/1027814/83328387-9474fe00-a250-11ea-9521-de788db96de5.PNG)

Re: Keyboard / Mouse Shortcuts
The Default is Ctrl+Shift+Up to increment and Ctrl+Shift+Down to decrement. In order to adjust the shortcuts, you need to get into the extension options page. There's two ways.

1. After you get the icon on your toolbar, you can click **URLI Extension Icon > Gear Icon (Options)**
2. Or via the FireFox three bar menu icon, click: **Menu >Add-ons > Extensions > URL Incrementer > Options**

![3](https://user-images.githubusercontent.com/1027814/83329059-2d0d7d00-a255-11ea-83ef-98f055160369.PNG)

From there you can adjust the shortcuts to whatever key and mouse combination you want.

![4](https://user-images.githubusercontent.com/1027814/83329069-33035e00-a255-11ea-8574-780fa3fe8643.PNG)

Re: Email Address
Sorry you couldn't find it and had to get on GitHub for help. The only reason I didn't put my email on the Help Page is to avoid getting a ton of junk mail from harvesting crawlers who look for it on the web. Because of your feedback, I'll try to put it on the Help page as soon as I am able to.

Hope this helps!

**Comment by ublokr** [comment]
Hi, thanks for the quick reply, and please forgive if I sounded a bit short-tempered.
I'm pretty sure the three add-ons are added in my Firefox. 


Do I maybe need to allow them to work in private windows? But as far as I know I'm not using private windows. And, looking now, I don't see where I have that switch to allow it, though I think I came across it earlier.

I don't see the icons listed in the Customize screen (of which I was completely oblivious and it never occurred to me to check out). Here's the total of what I see.


If they are installed, they aren't behaving as you describe. To test, I duck-duck-go'd myself randomly to a url ending in a numberhttps://www.mmnt.net/db/0/0/212.85.104.184and tried Ctrl-Shift+Up and Down. Nothing.

I also failed to get to options for the add-ons. Since I have no icons, I took the alternative approach through Mozilla 3-bar menu | add-ons | extensions. The URLI entry has its own three-bar thing, but under it only this

Oh, OK, under manage I now see where I can select use in private windows
Trying that, AHA! Now the icon appears in toolbar.  I guess I'm using private windows.
But now trying Ctrl-Shift-Up and Down still doesn't flip the URL above (which would probably get me to a non-existent url, actually).  I think these keystrokes may be bespoke, since doing them moves the focus (highlighted text) on the above url's page, and, on the Add-ons Manager page, it causes the text of your help instructions to scroll to the top.  

If I click the URLI icon in the toolbar, nothing happens. If I right-click it, I get a menu, but I don't see OPTIONS on it where I can change the keystrokes for incrementing.
I guess crawlers and bots are now smart enough to back-translate jjthaden at flash dot net, right?

-John 

    On Saturday, May 30, 2020, 8:56:47 AM CDT, <notifications@github.com> wrote:  
 
 


Hi @ublokr ,

I'll try to address your issues one by one. FireFox is also not my main browser, but I'll reply to the browser-specific issues as well. All screenshots below are from FireFox 76.0.1

Re:Toolbar Icon
So, after you install URLI (or any extension), the toolbar icon normally shows up on the toolbar near the three bar menu icon (Menu) on the right side of the address bar. It's the URL+ icon underlined in red below.



It is a dark icon, so if your toolbar is a custom dark one, it may not stand out. If you don't have enough room (like having a lot of add-ons installed), it may also not be there. To get it there, Click Menu > Customize (Paint Brush Icon) and you'll be taken to this screen where you should see the extension icon and you can drag it onto your toolbar or the overflow menu. Click the Done button at the bottom of the screen when finished.



Re: Keyboard / Mouse Shortcuts
The Default is Ctrl+Shift+Up to increment and Ctrl+Shift+Down to decrement. In order to adjust the shortcuts, you need to get into the extension options page. There's two ways.
   
   - After you get the icon on your toolbar, you can click URLI Extension Icon > Gear Icon (Options)
   - Or via the FireFox three bar menu icon, click: Menu >Add-ons > Extensions > URL Incrementer > Options



From there you can adjust the shortcuts to whatever key and mouse combination you want.



Re: Email Address
Sorry you couldn't find it and had to get on GitHub for help. The only reason I didn't put my email on the Help Page is to avoid getting a ton of junk mail from harvesting crawlers who look for it on the web. Because of your feedback, I'll try to put it on the Help page as soon as I am able to.

Hope this helps!

**Comment by sixcious** [comment]
Hi again!

So long as you aren't using the extensions in Private Windows, there isn't any need to enable them in that mode. The fact that you're not seeing the extension icons on the Customize screen is very worrying though. I wasn't able to see your screenshot (if you attached one?), but I'm assuming all you're seeing on the Customize screen are the default FireFox icons like **History, Save Page, Find,** etc.? Is this correct?

Can you try going to your **FireFox Add-Ons Manager Page** by entering the **Ctrl+Shift+A** FireFox shortcut key or via **Menu > Add-ons**? This will take you to the following screen. This will make sure the extensions are actually _both_ installed and enabled. Can you see that they are there and that they are **enabled** by checking that the **toggle is blue**? If you see the **purple mask icon** next to them (like in the screenshot below), that means you have them allowed in Private Windows, but this isn't required. The important thing is that they are visible AND enabled.

FireFox Add-Ons Manager Page Screenshot:
![1](https://user-images.githubusercontent.com/1027814/83334142-76b89080-a272-11ea-8744-6a0acc6acee8.PNG)

Re: Options Page
On the Add-Ons Manager page, you should be able to click on the extension row for URL Incrementer and this will take you to the Extension's main page. This isn't obvious, but there are three panels there: **Details, Options, Permissions** that you can click on to take you to the different parts. You should be able to click on **Options** to get to the extension's options page where you can change the shortcuts.

Extension Main Page with Details, Options, Permissions Screenshot:
![2](https://user-images.githubusercontent.com/1027814/83334788-ec266000-a276-11ea-90e5-3f7e6e5ef20a.PNG)

OK, after reading your second half of your post, I would try to get off the Private Window and just enter a Normal Browser Window (no purple mask icon). It seems like your problem now is that you can't get the shortcut keys to work, and that you can't get into the Options Page to adjust the shortcut keys? And you still can't see the icon in the toolbar? All three of these are huge issues.

Re: Shortcut Keys
The shortcut keys won't work if you still have focus on the URL address bar. You just need to get the focus onto anywhere else on the browser screen (e.g. clicking on the white-space on the page itself would do the trick). I was able to increment the URL you gave me using the default Ctrl+Shift+Up (it changed the 212 to a 213, leading to a 404 Page) so I don't think it's an issue, but you should definitely try changing it just to rule it out as your environment may be different than mine and maybe you have another extension that is using that shortcut.

Can you by any chance share a screenshot of your Add-ons Manager Page, Customize Screen, and Toolbar? It would make troubleshooting much easier.

No worries on the tense of post; I hope you will get URLI working and that this helps a bit in steering you in the right direction. :)

**Comment by ublokr** [comment]
I missed the three tabs, and the one named options. Thanks.
In private mode, the Ctrl-Shift-Up and Down don't increment. Focus is not on the url field. My add-ons are Duck Duck Go Privacy Essentials, Duck Duck Go Search, your three add-ons, and Zoom Scheduler.
This (and attached) is the checkbox in Firefox privacy options for always private window

Unchecking it (caused Firefox reboot), now openinghttps://www.mmnt.net/db/0/0/87.245.132.186and, with focus on white space, Ctrl-Shift-Up (or Down), still no incrementing. It just changes the focus to a particular line of text in the page. I tried this with the purple mask showing and not showing on URLI (allow/disallow in private). Same result. Also, your + and - icons show at top. When I click them while on the above page, nothing.
In summary then, all three icons now show in the toolbar. Left-clicking them does nothing at all. Right-clicking them brings up a menu that includes "manage extension" and from that I can get to the options tab (the + and - don't have options tabs). In(de)crement shortcuts fail, as does clicking on the + or - icons. This is true regardless of where focus is.
-John 

    On Saturday, May 30, 2020, 12:33:33 PM CDT, <notifications@github.com> wrote:  
 
 


Hi again!

So long as you aren't using the extensions in Private Windows, there isn't any need to enable them in that mode. The fact that you're not seeing the extension icons on the Customize screen is very worrying though. I wasn't able to see your screenshot (if you attached one?), but I'm assuming all you're seeing on the Customize screen are the default FireFox icons like History, Save Page, Find, etc.? Is this correct?

Can you try going to your FireFox Add-Ons Manager Page by entering the Ctrl+Shift+A FireFox shortcut key or via Menu > Add-ons? This will take you to the following screen. This will make sure the extensions are actually both installed and enabled. Can you see that they are there and that they are enabled by checking that the toggle is blue? If you see the purple mask icon next to them (like in the screenshot below), that means you have them allowed in Private Windows, but this isn't required. The important thing is that they are visible AND enabled.

FireFox Add-Ons Manager Page Screenshot:


Re: Options Page
On the Add-Ons Manager page, you should be able to click on the extension row for URL Incrementer and this will take you to the Extension's main page. This isn't obvious, but there are three panels there: Details, Options, Permissions that you can click on to take you to the different parts. You should be able to click on Options to get to the extension's options page where you can change the shortcuts.

Extension Main Page with Details, Options, Permissions Screenshot:


OK, after reading your second half of your post, I would try to get off the Private Window and just enter a Normal Browser Window (no purple mask icon). It seems like your problem now is that you can't get the shortcut keys to work, and that you can't get into the Options Page to adjust the shortcut keys? And you still can't see the icon in the toolbar? All three of these are huge issues.

Re: Shortcut Keys
The shortcut keys won't work if you still have focus on the URL address bar. You just need to get the focus onto anywhere else on the browser screen (e.g. clicking on the white-space on the page itself would do the trick). I was able to increment the URL you gave me using the default Ctrl+Shift+Up (it changed the 212 to a 213, leading to a 404 Page) so I don't think it's an issue, but you should definitely try changing it just to rule it out as your environment may be different than mine and maybe you have another extension that is using that shortcut.

Can you by any chance share a screenshot of your Add-ons Manager Page, Customize Screen, and Toolbar? It would make troubleshooting much easier.

No worries on the tense of post; I hope you will get URLI working and that this helps a bit in steering you in the right direction. :)

**Comment by roysix** [comment]
Hi again,

Sorry, but I'm just not able to see any of your screenshots here on GitHub, so it's hard to say what's going on.  Are you commenting on GitHub and dragging & dropping the images into the "Write/Preview" box at the https://github.com/roysix/url-incrementer/issues/3 URL or just replying via email and attaching them that way? If it's easier, you can email me the images you've been trying to share at urlincrementer AT gmail DOT com

I'm starting to think that the problem might be with the Private Window and that I think you **installed** it in a Private Window, causing some issue with installation. I know it's a drag, but can you try uninstalling the extensions and then installing them in a Normal Window (not Private Window)? And then try clicking on the toolbar icons one time in a Normal Window (to rule out the Private Window thing)?

There's some limitations with URLI in Private Window mode, with the Popup not able to work, but you should still see a message explaining this. This is the screenshot you should be seeing in Private Window when you click the URLI icon. I'm guessing you're not even seeing this and simply **nothing** is showing up?:
![NW](https://user-images.githubusercontent.com/1027814/83340103-5274a800-a2a2-11ea-9b62-1a3f3832e444.PNG)

Have you tried maybe testing a different URL to increment, like say https://danbooru.donmai.us/posts/3081914 or something else?

One more thing to try would be to disable all other extensions temporarily (on the Add-ons Manager page), and restarting FireFox one last time to rule out another extension potentially causing problems.

Finally, although I hate to admit it, you could try a different extension. There's the [Next Prev Page](https://addons.mozilla.org/en-US/firefox/addon/nextprev-page/) extension, though it doesn't have the same features as URLI. Let me know if that works for you any better.

Hope this helps.

**Comment by sixcious** [comment]
Hi again,

Sorry, but I'm just not able to see any of your screenshots here on GitHub, so it's hard to say what's going on.  Are you commenting on GitHub and dragging & dropping the images into the "Write/Preview" box at the https://github.com/roysix/url-incrementer/issues/3 URL or just replying via email and attaching them that way? If it's easier, you can email me the images you've been trying to share at urlincrementer AT gmail DOT com

I'm starting to think that the problem might be with the Private Window and that I think you **installed** it in a Private Window, causing some issue with installation. I know it's a drag, but can you try uninstalling the extensions and then installing them in a Normal Window (not Private Window)? And then try clicking on the toolbar icons one time in a Normal Window (to rule out the Private Window thing)?

There's some limitations with URLI in Private Window mode, with the Popup not able to work, but you should still see a message explaining this. This is the screenshot you should be seeing in Private Window when you click the URLI icon. I'm guessing you're not even seeing this and simply **nothing** is showing up?:
![NW](https://user-images.githubusercontent.com/1027814/83340103-5274a800-a2a2-11ea-9b62-1a3f3832e444.PNG)

Have you tried maybe testing a different URL to increment, like say https://github.com/roysix/url-incrementer/issues/3 or something else?

One more thing to try would be to disable all other extensions temporarily (on the Add-ons Manager page), and restarting FireFox one last time to rule out another extension potentially causing problems.

Finally, although I hate to admit it, you could try a different extension. There's the [Next Prev Page](https://addons.mozilla.org/en-US/firefox/addon/nextprev-page/) extension, though it doesn't have the same features as URLI. Let me know if that works for you any better.

Hope this helps.

**Comment by ublokr** [comment]
I'll forward you all the emails I sent, then shall report on the reinstallation. So here first the emails....

-John 

    On Saturday, May 30, 2020, 6:26:35 PM CDT, <notifications@github.com> wrote:  
 
 


Hi again,

Sorry, but I'm just not able to see any of your screenshots here on GitHub, so it's hard to say what's going on. Are you commenting on GitHub and dragging & dropping the images into the "Write/Preview" box at the #3 URL or just replying via email and attaching them that way? If it's easier, you can email me the images you've been trying to share at urlincrementer AT gmail DOT com

I'm starting to think that the problem might be with the Private Window and that I think you installed it in a Private Window, causing some issue with installation. I know it's a drag, but can you try uninstalling the extensions and then installing them in a Normal Window (not Private Window)? And then try clicking on the toolbar icons one time in a Normal Window (to rule out the Private Window thing)?

There's some limitations with URLI in Private Window mode, with the Popup not able to work, but you should still see a message explaining this. This is the screenshot you should be seeing in Private Window when you click the URLI icon. I'm guessing you're not even seeing this and simply nothing is showing up?:


Have you tried maybe testing a different URL to increment, like say #3 or something else?

One more thing to try would be to disable all other extensions temporarily (on the Add-ons Manager page), and restarting FireFox one last time to rule out another extension potentially causing problems.

Finally, although I hate to admit it, you could try a different extension. There's the Next Prev Page extension, though it doesn't have the same features as URLI. Let me know if that works for you any better.

Hope this helps.

**Comment by ublokr** [comment]
I did install it while in private window mode.
I did all by replying to emails. I think my replies are bundled or something. I only saw one sent one to forward. Should have pics.
I see no warning or message about popups.

OK, all is uninstalled/reinstalled, not in PW. Testing....
Well, I'm afraid this isn't going to be so helpful to you, I botched the testing. First tests were negative, but then I noticed URLI actually hadn't installed (but I was sure it had!!). I tried a bunch of things.
It is now working both in private and non-private mode, with it and the +/- add-ons set to work in private. This didn't happen right away, but after I deactivated the two duck duck go add-ons and the Zoom Scheduler add-on, then it worked in non-private mode. Then I started re-activating things. Still worked. Then I made the duck duck go privacy add-on, the zoom add-on and your three add-ons enabled for private browsing.  Still works.  

The upshot is it now works and I can be private.  Wish the solution were more clear, or that I had more time to redo it correctly.  Hope this helps anyway.
Thanks for taking the time. I'm up and running!

-John

 

    On Saturday, May 30, 2020, 6:26:35 PM CDT, <notifications@github.com> wrote:  
 
 


Hi again,

Sorry, but I'm just not able to see any of your screenshots here on GitHub, so it's hard to say what's going on. Are you commenting on GitHub and dragging & dropping the images into the "Write/Preview" box at the #3 URL or just replying via email and attaching them that way? If it's easier, you can email me the images you've been trying to share at urlincrementer AT gmail DOT com

I'm starting to think that the problem might be with the Private Window and that I think you installed it in a Private Window, causing some issue with installation. I know it's a drag, but can you try uninstalling the extensions and then installing them in a Normal Window (not Private Window)? And then try clicking on the toolbar icons one time in a Normal Window (to rule out the Private Window thing)?

There's some limitations with URLI in Private Window mode, with the Popup not able to work, but you should still see a message explaining this. This is the screenshot you should be seeing in Private Window when you click the URLI icon. I'm guessing you're not even seeing this and simply nothing is showing up?:


Have you tried maybe testing a different URL to increment, like say #3 or something else?

One more thing to try would be to disable all other extensions temporarily (on the Add-ons Manager page), and restarting FireFox one last time to rule out another extension potentially causing problems.

Finally, although I hate to admit it, you could try a different extension. There's the Next Prev Page extension, though it doesn't have the same features as URLI. Let me know if that works for you any better.

Hope this helps.

**Comment by sixcious** [comment]
Thanks for the reply, I'm super glad you were able to find a solution! I was really stumped there and about to give up. I can see the picture in the email you sent; I never tried enabling that Private Window checkbox you had set, so I'll have to try testing that one out. I will definitely add a small warning in the Help Guide about extension compatibility and Private Window mode and a note to try re-installing everything just in case this happens to anyone again.

If everything's working right, and if you have a few minutes free time, could you **please** help rate the extension on FireFox? URLI just got its first 1-star rating today and it would **really** help. If that rating happened to be from you, I'd especially appreciate it if you could consider changing it because a 1 star is quite damaging to extensions with fewer ratings (but I understand if you won't).

https://addons.mozilla.org/en-US/firefox/addon/url-incrementer/

Thanks again!

**Comment by ublokr** [comment]
I had started to rate when I saw your request to first email. Don't think it got done but I'll check and revise to 5s if it did. In any case, I'll rate it and U'm really pleased you syruggled theough this with me!

Sent from AT&T Yahoo Mail on Android 
 
  On Sat, May 30, 2020 at 8:53 PM, <notifications@github.com> wrote:   


Thanks for the reply, I'm super glad you were able to find a solution! I was really stumped there and about to give up. I can see the picture in the email you sent; I never tried enabling that Private Window checkbox you had set, so I'll have to try testing that one out. I will definitely add a small warning in the Help Guide about extension compatibility and Private Window mode and a note to try re-installing everything just in case this happens to anyone again.

If everything's working right, and if you have a few minutes free time, could you please help rate the extension on FireFox? URLI just got its first 1-star rating today and it would really help. If that rating happened to be from you, I'd especially appreciate it if you could consider changing it because a 1 star is quite damaging to extensions with fewer ratings (but I understand if you won't).

https://addons.mozilla.org/en-US/firefox/addon/url-incrementer/

Thanks again!

**Comment by sixcious** [comment]
Thanks! Yes, I'd really appreciate if you could do that, but it's up to you. It's unfortunately still a 1 star rating at the moment. I can't seem to reply to it since it's a no comment rating, so it must have been left unfinished like you said, but it did indeed go through and brought the rating down .5 points unfortunately.

On a positive note, thanks to you bringing this issue up, I updated the help guide with an actual email address people can use and a warning about Private Windows with link to this issue so hopefully no one else will have to go through all this trouble again.
