### ISSUE TITLE
negative increment 

### ISSUE THREAD

**Issue by CarlFK** [roysix/url-incrementer#7]
I am on page 123, and I want to go backwards.

-1 is not allowed.

**Comment by sixcious** [comment]
Hi CarlFK

URLI has a `Decrement` action to cover that use case.  After you click URLI's Toolbar Icon and click the Accept Button in the UI Window, you should see both `+` (Increment) and `-` (Decrement) buttons. Doing it this way gives you flexibility in which direction you want to go at any given time instead of locking you into one direction with only one action (incrementing a negative interval).

You can navigate your browser to `chrome://extensions/shortcuts` to assign a Decrement shortcut key if you're using keyboard shortcuts. If you're on the Firefox version, the shortcuts are built into URLI's Options screen (for the time being).

Hope that helps!

**Comment by CarlFK** [comment]
ah!  I wanted this for the auto option, and I see there is a Decrement choice there.  derp.  closed!
